EVG-13301: Merge rollups when saving new perf data
evergreen-ci/cedar pull request #295
Opened 2020-12-01 17:00 UTC by julianedwards

JIRA: https://jira.mongodb.org/browse/EVG-13301

There are two ways to add rollups: (1) via `PerformanceResult.SaveNew` and (2) via `PerformanceResult.MergeRollups`. The latter ensures no duplicate rollup names are added and checks against the version of a rollup (if it exists already). This PR refactors `PerformanceResult.SaveNew` to use `MergeRollups` instead of inserting the rollups as they are.

2020-12-01 17:06 UTC, ancostas requested changes
Looks good modulo: can we add a test showing it does error when user attempts to save duplicate rollups?

2020-12-01 17:12 UTC, Kimchelly approved these changes

2020-12-01 20:17 UTC, julianedwards commented
Yeah lint is failing on master, I am going to look into it separately. So the design of `MergeRollups` isn't that it will fail but it instead just take the most recent rollup with the given name (hence, the version check).

2020-12-02 16:25 UTC, ancostas approved these changes
Ok

2020-12-02 16:52 UTC, merged